name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: 'Tar-devsecops'   # set this to your application's name
  PYTHON_VERSION: '3.12'
on:
  push:
    branches:
      
main

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
     actions: read
     contents: read
     security-events: write

    steps:
      
uses: actions/checkout@v4

      
name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

      
name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
name: Install dependencies
    run: pip install -r requirements.txt

      
name: Analyze with CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
name: Perform CodeQL Analysis
uses: github/codeql-action/analyze@v3
with:
 category: "/language:${{matrix.language}}"

      
name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
        name: flask-api
        path: |.!venv/
deploy:
  runs-on: ubuntu-20.04
  needs: build
  environment:
    name: 'production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      
name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: flask-api
        path: .

      
name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
